// vue-todo/src/App.vue
<template>
  <div>
    <div>
      <input v-model="newName" placeholder="Task name" />
      <select v-model="newPriority">
        <option>low</option><option>medium</option><option>high</option>
      </select>
      <button @click="addTask">Add</button>
    </div>
    <ul>
      <li v-for="task in tasks" :key="task.id">
        <template v-if="editId !== task.id">
          {{ task.name }} ({{ task.priority }})
          <button @click="editId = task.id">Edit</button>
          <button @click="removeTask(task.id)">Delete</button>
        </template>
        <template v-else>
          <input v-model="task.name" />
          <select v-model="task.priority">
            <option>low</option><option>medium</option><option>high</option>
          </select>
          <button @click="editId = null">Save</button>
        </template>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { ref } from 'vue';
const tasks = ref([]);
const newName = ref('');
const newPriority = ref('low');
const editId = ref(null);

const addTask = () => {
  tasks.value.push({ id: Date.now(), name: newName.value, priority: newPriority.value });
  newName.value = '';
};
const removeTask = (id) => {
  tasks.value = tasks.value.filter(t => t.id !== id);
};
</script>

// react-todo/src/App.js

import React, { useState, useCallback } from 'react';

function App() {
  const [tasks, setTasks] = useState([]);
  const [newName, setNewName] = useState('');
  const [newPriority, setNewPriority] = useState('low');
  const [editId, setEditId] = useState(null);

  const addTask = useCallback(() => {
    setTasks(prev => [...prev, { id: Date.now(), name: newName, priority: newPriority }]);
    setNewName('');
  }, [newName, newPriority]);

  const removeTask = useCallback(id => {
    setTasks(prev => prev.filter(t => t.id !== id));
  }, []);

  const updateTask = useCallback((id, field, value) => {
    setTasks(prev => prev.map(t => t.id === id ? { ...t, [field]: value } : t));
  }, []);

  return (
    <div>
      <div>
        <input value={newName} onChange={e => setNewName(e.target.value)} placeholder="Task name" />
        <select value={newPriority} onChange={e => setNewPriority(e.target.value)}>
          <option>low</option><option>medium</option><option>high</option>
        </select>
        <button onClick={addTask}>Add</button>
      </div>
      <ul>
        {tasks.map(task => (
          <li key={task.id}>
            {editId === task.id ? (
              <>
                <input defaultValue={task.name} onBlur={e => updateTask(task.id, 'name', e.target.value)} />
                <select defaultValue={task.priority} onChange={e => updateTask(task.id, 'priority', e.target.value)}>
                  <option>low</option><option>medium</option><option>high</option>
                </select>
                <button onClick={() => setEditId(null)}>Save</button>
              </>
            ) : (
              <>
                {task.name} ({task.priority})
                <button onClick={() => setEditId(task.id)}>Edit</button>
                <button onClick={() => removeTask(task.id)}>Delete</button>
              </>
            )}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;
